// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Lucene.Net.Odm.Mappers
{
    using Lucene.Net.Odm.Mapping;
    using Lucene.Net.Odm.Helpers;
    using System;
    
    
    #line 1 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class CompiledDocumentMapperTemplate : CompiledDocumentMapperTemplateBase
    {
        public virtual string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing Sys" +
                    "tem.Globalization;\r\n\r\nusing Lucene.Net.Documents;\r\nusing Lucene.Net.Odm.Mapping;" +
                    "\r\n\r\n\r\nnamespace Lucene.Net.Odm.Mappers\r\n{\r\n    public partial class ");
            
            #line 16 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ShortModelName));
            
            #line default
            #line hidden
            this.Write("CompiledMapper : Lucene.Net.Odm.Mappers.ICompiledMapper<");
            
            #line 16 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        public Document GetDocument(");
            
            #line 18 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));
            
            #line default
            #line hidden
            this.Write(" model)\r\n        {\r\n            Document document = new Document();\r\n\r\n        ");
            
            #line 22 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
 foreach (PropertyMapping propMapping in DocumentMapping.PropertyMappings) { 
            
            #line default
            #line hidden
            this.Write("            document.Add(model.");
            
            #line 23 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propMapping.PropertyInfo.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n        ");
            
            #line 24 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n            return document;\r\n        }\r\n\r\n        public ");
            
            #line 29 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));
            
            #line default
            #line hidden
            this.Write(" GetModel(Document document)\r\n        {\r\n            ");
            
            #line 31 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));
            
            #line default
            #line hidden
            this.Write(" model = new ");
            
            #line 31 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));
            
            #line default
            #line hidden
            this.Write("();\r\n\r\n            ");
            
            #line 33 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
 foreach (PropertyMapping propMapping in DocumentMapping.PropertyMappings) { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 34 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
 if (DataHelper.IsGenericEnumerable(propMapping.PropertyInfo.PropertyType)) { 
            
            #line default
            #line hidden
            this.Write("                    string[] ");
            
            #line 35 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propMapping.PropertyInfo.Name));
            
            #line default
            #line hidden
            this.Write("Values = document.GetValues();\r\n                    ");
            
            #line 36 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
 if (propMapping.FieldConfiguration.IsRequired) { 
            
            #line default
            #line hidden
            this.Write("                        \r\n                    ");
            
            #line 38 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                    ");
            
            #line 39 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 40 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                    ");
            
            #line 41 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
 if (propMapping.FieldConfiguration.IsRequired) { 
            
            #line default
            #line hidden
            this.Write("                        model.");
            
            #line 42 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propMapping.PropertyInfo.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 42 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyRaw(propMapping.PropertyInfo.PropertyType, String.Format("document.Get(\"{0}\")", propMapping.FieldConfiguration.FieldName))));
            
            #line default
            #line hidden
            this.Write(";\r\n                    ");
            
            #line 43 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                        string ");
            
            #line 44 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propMapping.PropertyInfo.Name));
            
            #line default
            #line hidden
            this.Write("Value = document.Get(\"");
            
            #line 44 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propMapping.FieldConfiguration.FieldName));
            
            #line default
            #line hidden
            this.Write("\");\r\n                        if (!String.IsNullOrEmpty(");
            
            #line 45 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propMapping.PropertyInfo.Name));
            
            #line default
            #line hidden
            this.Write("Value)) {\r\n                            model.");
            
            #line 46 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propMapping.PropertyInfo.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 46 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPropertyRaw(propMapping.PropertyInfo.PropertyType, propMapping.PropertyInfo.Name + "value")));
            
            #line default
            #line hidden
            this.Write(";\r\n                        }\r\n                    ");
            
            #line 48 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 49 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 50 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n            return model;\r\n        }\r\n    }\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 57 "D:\Git\DSS\flucene\Flucene\Mappers\CompiledDocumentMapperTemplate.tt"

    const string enumFormat = "({0})Enum.Parse(typeof({0}), {1}, true)";
    const string convertFormat = "({0})Convert.ChangeType({1}, typeof({2}), CultureInfo.InvariantCulture)";

    public string ShortModelName { get; set; }
    public string ModelName { get; set; }
    public dynamic DocumentMapping {get; set; }

    private string GetPropertyRaw(Type propertyType, string stringPropValue)
    {
        if (propertyType == typeof(string))
        {
            return stringPropValue;
        }
        else if (propertyType.IsEnum)
        {
            return String.Format(enumFormat, propertyType, stringPropValue);
        }
        else if (propertyType == typeof(DateTime))
        {
            return String.Format("DataHelper.ParseDateTime({0})", stringPropValue);
        }
        else if (DataHelper.IsConvertibleType(propertyType))
        {
            return String.Format(convertFormat, propertyType.Name, stringPropValue, propertyType.Name);
        }
        else if (DataHelper.IsNullableType(propertyType))
        {
            Type baseType = Nullable.GetUnderlyingType(propertyType);
            if (DataHelper.IsConvertibleType(baseType))
                return String.Format(convertFormat, baseType.Name + "?", stringPropValue, baseType.Name);
            else
                throw new ArgumentException("This type is not supported.");
        }
        else
        {
            throw new ArgumentException("propertyType");
        }
    }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class CompiledDocumentMapperTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
